# To install this environment:
# micromamba create -f environment.yaml -y
name: "chaz"
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pip:
    - -e .
  - datashader
  - fastparquet
  - geopandas
  - geoviews
  - hatch
  - holoviews
  - jupyter
  - jupyter_bokeh
  - netCDF4
  - notebook
  - numpy
  - matplotlib
  - pyarrow
  - bioconda::snakemake
  - bioconda::snakemake-executor-plugin-slurm
  - seaborn
  - tqdm
  - xarray
